version: '3.5'
services:
  zeo:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: iaurban-dev
    volumes:
      - ./var/blobstorage:/home/imio/urban/var/blobstorage
      - ./var/filestorage:/home/imio/urban/var/filestorage
      - ./dev.cfg:/home/imio/urban/dev.cfg
      - ./base.cfg:/home/imio/urban/base.cfg
      - ./src:/home/imio/urban/src
    command: zeoserver fg
  instance:
    image: iaurban-dev:latest
    ports:
      - 8081:8081
    depends_on:
      - libreoffice
    links:
      - zeo:db
    environment:
      - OO_PORT=2002
    volumes:
      - ./var/urban:/home/imio/urban/var/urban
      - ./src:/home/imio/urban/src
    command: instance fg
  libreoffice:
    image: iaurban-dev:latest
    command: soffice --invisible --headless --accept="socket,port=2002;urp;"
