FROM docker-staging.imio.be/iaurban/mutual:latest
ARG user_id=1000
ARG group_id=1000
ENV ENVIRONMENT dev
RUN rm -rf /home/imio/.local &&  rm -rf /home/imio/.cache && usermod -u $user_id imio && groupmod -g $group_id -o imio && chown -R $user_id:$group_id /home/imio
# Removed libtiff5-dev
RUN buildDeps="libpq-dev wget git python-virtualenv gcc libc6-dev libpcre3-dev libssl-dev libxml2-dev libxslt1-dev libbz2-dev libffi-dev libjpeg62-dev libopenjp2-7-dev zlib1g-dev python-dev" \
  && apt-get update \
  && apt-get install -y --no-install-recommends $buildDeps \
  && mkdir -p /home/imio/urban \
  && chown imio:imio -R /home/imio/urban/
# COPY *.cfg *.py *.txt /home/imio/urban/
COPY *.cfg $URBAN_DIR
USER imio
RUN pip install --user -I -r requirements.txt \
  && buildout -c dev.cfg
USER root
RUN apt-get purge -y --auto-remove $buildDeps \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /home/imio/.buildout/downloads/*
