version: '3.5'
services:
  zeo:
    build:
      context: .
    image: urbanzeo
    user: imio
    command: bin/zeoserver fg
  instance:
    image: urbanzeo:latest
    user: imio
    ports:
      - 8081:8081
    links:
      - zeo:db
    command: bin/instance fg

volumes:
  data:
