version: '3.5'
services:
  zeo:
    build:
      context: .
    image: urbanzeo
    command: zeoserver
  instance:
    image: urbanzeo:latest
    ports:
      - 8081:8081
    links:
      - zeo:db
    command: instance

volumes:
  data:
