version: '3.5'
services:
  zeo:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: iaurban-dev
    volumes:
      - ./var/blobstorage:/home/imio/urban/var/blobstorage
      - ./var/filestorage:/home/imio/urban/var/filestorage
      - ./var/urban/services.cfg:/home/imio/urban/var/urban/services.cfg
      - ./dev.cfg:/home/imio/urban/dev.cfg
      - ./base.cfg:/home/imio/urban/base.cfg
      - ./src:/home/imio/urban/src
    command: zeoserver fg
  instance:
    image: iaurban-dev:latest
    ports:
      - 8081:8081
    links:
      - zeo:db
    environment:
      - OO_PORT=2003
    volumes:
      - ./src:/home/imio/urban/src
    command: instance fg
